export const usStates = [
	{ name: 'AL', value: 'AL', label: 'Alabama' },
	{ name: 'AK', value: 'AK', label: 'Alaska' },
	{ name: 'AZ', value: 'AZ', label: 'Arizona' },
	{ name: 'AR', value: 'AR', label: 'Arkansas' },
	{ name: 'CA', value: 'CA', label: 'California' },
	{ name: 'CO', value: 'CO', label: 'Colorado' },
	{ name: 'CT', value: 'CT', label: 'Connecticut' },
	{ name: 'DE', value: 'DE', label: 'Delaware' },
	{ name: 'DC', value: 'DC', label: 'District of Columbia' },
	{ name: 'FL', value: 'FL', label: 'Florida' },
	{ name: 'GA', value: 'GA', label: 'Georgia' },
	{ name: 'HI', value: 'HI', label: 'Hawaii' },
	{ name: 'ID', value: 'ID', label: 'Idaho' },
	{ name: 'IL', value: 'IL', label: 'Illinois' },
	{ name: 'IN', value: 'IN', label: 'Indiana' },
	{ name: 'IA', value: 'IA', label: 'Iowa' },
	{ name: 'KS', value: 'KS', label: 'Kansas' },
	{ name: 'KY', value: 'KY', label: 'Kentucky' },
	{ name: 'LA', value: 'LA', label: 'Louisiana' },
	{ name: 'ME', value: 'ME', label: 'Maine' },
	{ name: 'MD', value: 'MD', label: 'Maryland' },
	{ name: 'MA', value: 'MA', label: 'Massachusetts' },
	{ name: 'MI', value: 'MI', label: 'Michigan' },
	{ name: 'MN', value: 'MN', label: 'Minnesota' },
	{ name: 'MS', value: 'MS', label: 'Mississippi' },
	{ name: 'MO', value: 'MO', label: 'Missouri' },
	{ name: 'MT', value: 'MT', label: 'Montana' },
	{ name: 'NE', value: 'NE', label: 'Nebraska' },
	{ name: 'NV', value: 'NV', label: 'Nevada' },
	{ name: 'NH', value: 'NH', label: 'New Hampshire' },
	{ name: 'NJ', value: 'NJ', label: 'New Jersey' },
	{ name: 'NM', value: 'NM', label: 'New Mexico' },
	{ name: 'NY', value: 'NY', label: 'New York' },
	{ name: 'NC', value: 'NC', label: 'North Carolina' },
	{ name: 'ND', value: 'ND', label: 'North Dakota' },
	{ name: 'OH', value: 'OH', label: 'Ohio' },
	{ name: 'OK', value: 'OK', label: 'Oklahoma' },
	{ name: 'OR', value: 'OR', label: 'Oregon' },
	{ name: 'PA', value: 'PA', label: 'Pennsylvania' },
	{ name: 'RI', value: 'RI', label: 'Rhode Island' },
	{ name: 'SC', value: 'SC', label: 'South Carolina' },
	{ name: 'SD', value: 'SD', label: 'South Dakota' },
	{ name: 'TN', value: 'TN', label: 'Tennessee' },
	{ name: 'TX', value: 'TX', label: 'Texas' },
	{ name: 'UT', value: 'UT', label: 'Utah' },
	{ name: 'VT', value: 'VT', label: 'Vermont' },
	{ name: 'VA', value: 'VA', label: 'Virginia' },
	{ name: 'WA', value: 'WA', label: 'Washington' },
	{ name: 'WV', value: 'WV', label: 'West Virginia' },
	{ name: 'WI', value: 'WI', label: 'Wisconsin' },
	{ name: 'WY', value: 'WY', label: 'Wyoming' },
];
